export enum Paths {
	home = '/*',
	movies = '/movies',
	tvShows = '/tv-shows',
	person = '/person',
	search = '/search=',
	page = '/page=',
}

export enum API {
	base = 'https://api.themoviedb.org/3/',
	requestToken = 'authentication/token/new',
	authenticate = `https://www.themoviedb.org/authenticate/`,
	redirect = '?redirect_to=http://localhost:3000/approved',
	authenticateWithToken = 'authentication/session/new',
	deleteSession = 'authentication/session',
	movies = 'movie/',
	tvShows = 'tv/',
	popular = 'popular',
	certification = 'certification/',
	genre = 'genre/',
	discover = 'discover/',
	list = 'list',
	byCertification = '&sort_by=popularity.desc&certification_country=US&certification=',
	byGenre = '&sort_by=popularity.desc&with_genres=',
	moviesMinYear = '&sort_by=popularity.desc&primary_release_date.gte=',
	moviesMaxYear = '&primary_release_date.lte=',
	tvShowsMinYear = '&sort_by=popularity.desc&first_air_date.gte=',
	tvShowsMaxYear = '&first_air_date.lte=',
	images = 'https://image.tmdb.org/t/p/',
	imageWidth200 = 'w200',
	search = 'search/multi',
}
